server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: loveshopping-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soloXX/loveshopping_config.git
          username: soloXX
          password: Xx**4932351